[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ctn-monitor-etl"
version = "0.1.0"
description = "Compulsory COVID Testing Monitor ETL modules"
readme = "README.md"
requires-python = "~=3.13"
license = {text = "MIT"}
authors = [{name = "Jack Chan"}]
dependencies = [
    "fastparquet==2026.3.0",
    "openpyxl==3.1.5",
    "pandas==2.3.3",
    "pdfservices-sdk==4.0.0",
    "pyarrow==23.0.1",
    "python-dotenv==1.2.2",
    "requests==2.31.0",
]

[tool.setuptools.packages.find]
include = ["ctn_monitor*"]
